"""empty message

Revision ID: 920870898ca2
Revises: cf2fc5530f5d
Create Date: 2023-04-23 17:01:26.139511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920870898ca2'
down_revision = 'cf2fc5530f5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_hash')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
